name: Lint

on:
  push: {}
  pull_request: {}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup shfmt
        uses: pollenjp/setup-shfmt@v1

      - name: Install dependencies
        run: pnpm install

      - name: Run linter
        run: pnpm eslint
